// Initial Hardcoded Data
const INITIAL_CENTERS = [
  {
    id: 1,
    name: 'Kandy Teaching Hospital',
    type: 'Government Hospital',
    area: 'Kandy City',
    address: 'William Gopallawa Mawatha, Kandy 20000',
    phone: '+94 81 222 3337',
    hours: '24 Hours',
    services: ['Emergency', 'OPD', 'Surgery', 'Cardiology', 'Paediatrics'],
    rating: 4.5,
    distance: '0.8 km',
    available: true,
    tag: 'govt',
    coords: { lat: 7.2900, lng: 80.6343 },
    doctor_available: true,
  },
  {
    id: 2,
    name: 'Nalanda Medical Centre',
    type: 'Private Clinic',
    area: 'Peradeniya',
    address: 'No. 42 Peradeniya Road, Kandy',
    phone: '+94 81 238 7890',
    hours: '8:00 AM – 8:00 PM',
    services: ['OPD', 'Gynaecology', 'Dental', 'Laboratory'],
    rating: 4.7,
    distance: '2.3 km',
    available: true,
    tag: 'private',
    coords: { lat: 7.2683, lng: 80.5966 },
    doctor_available: false,
  },
  {
    id: 3,
    name: 'Hemas Hospital Kandy',
    type: 'Private Hospital',
    area: 'Katugastota',
    address: 'No. 289 Katugastota Road, Kandy',
    phone: '+94 81 205 5150',
    hours: '24 Hours',
    services: ['Emergency', 'OPD', 'Radiology', 'Orthopaedics', 'ICU'],
    rating: 4.8,
    distance: '3.1 km',
    available: true,
    tag: 'private',
    coords: { lat: 7.3116, lng: 80.6278 },
    doctor_available: true,
  },
  {
    id: 4,
    name: 'Durdans Kandy Medical Centre',
    type: 'Private Clinic',
    area: 'Kandy City',
    address: 'No. 100 Yatinuwara Veediya, Kandy',
    phone: '+94 81 220 0050',
    hours: '7:00 AM – 10:00 PM',
    services: ['OPD', 'Cardiology', 'Neurology', 'Laboratory', 'Pharmacy'],
    rating: 4.6,
    distance: '1.2 km',
    available: false,
    tag: 'private',
    coords: { lat: 7.2974, lng: 80.6358 },
    doctor_available: false,
  },
  {
    id: 5,
    name: 'Suwasetha Medical Centre',
    type: 'Private Clinic',
    area: 'Ampitiya',
    address: 'No. 15 Ampitiya Road, Kandy',
    phone: '+94 81 222 6688',
    hours: '8:30 AM – 6:00 PM',
    services: ['OPD', 'Paediatrics', 'Dental', 'Physiotherapy'],
    rating: 4.3,
    distance: '4.0 km',
    available: true,
    tag: 'private',
    coords: { lat: 7.2756, lng: 80.6512 },
    doctor_available: true,
  },
  {
    id: 6,
    name: 'Peradeniya Base Hospital',
    type: 'Government Hospital',
    area: 'Peradeniya',
    address: 'Galaha Road, Peradeniya, Kandy',
    phone: '+94 81 238 8011',
    hours: '24 Hours',
    services: ['Emergency', 'OPD', 'Mental Health', 'Surgery', 'Radiology'],
    rating: 4.2,
    distance: '5.5 km',
    available: true,
    tag: 'govt',
    coords: { lat: 7.2636, lng: 80.5938 },
    doctor_available: true,
  },
  {
    id: 7,
    name: 'Asiri Kandy Medical Hub',
    type: 'Private Hospital',
    area: 'Dharmaraja Junction',
    address: 'No. 67 D.S. Senanayake Veediya, Kandy',
    phone: '+94 81 222 4545',
    hours: '24 Hours',
    services: ['Emergency', 'OPD', 'Dermatology', 'ENT', 'Oncology'],
    rating: 4.9,
    distance: '0.5 km',
    available: true,
    tag: 'private',
    coords: { lat: 7.2958, lng: 80.6368 },
    doctor_available: true,
  },
  {
    id: 8,
    name: 'Kandy Lifecare Clinic',
    type: 'Private Clinic',
    area: 'Getambe',
    address: 'No. 22 Getambe Road, Kandy',
    phone: '+94 81 238 9922',
    hours: '9:00 AM – 7:00 PM',
    services: ['OPD', 'Gynaecology', 'Laboratory', 'Pharmacy'],
    rating: 4.4,
    distance: '3.7 km',
    available: false,
    tag: 'private',
    coords: { lat: 7.2823, lng: 80.6189 },
    doctor_available: false,
  },
  {
    id: 9,
    name: 'Udawatte Medical Centre',
    type: 'Private Clinic',
    area: 'Udawatte',
    address: 'No. 8 Udawatte Lane, Kandy',
    phone: '+94 81 222 1133',
    hours: '8:00 AM – 9:00 PM',
    services: ['OPD', 'Dental', 'Orthopaedics', 'Physiotherapy'],
    rating: 4.5,
    distance: '2.0 km',
    available: true,
    tag: 'private',
    coords: { lat: 7.2945, lng: 80.6400 },
    doctor_available: true,
  },
  {
    id: 10,
    name: "Lady Gordon Children's Hospital",
    type: 'Government Hospital',
    area: 'Kandy City',
    address: 'Sangamitta Mawatha, Kandy',
    phone: '+94 81 222 3535',
    hours: '24 Hours',
    services: ['Paediatrics', 'Emergency', 'NICU', 'Vaccination'],
    rating: 4.6,
    distance: '1.5 km',
    available: true,
    tag: 'govt',
    coords: { lat: 7.2902, lng: 80.6355 },
    doctor_available: true,
  },
  {
    id: 11,
    name: 'Mahiyawa Medical Centre',
    type: 'Private Clinic',
    area: 'Mahiyawa',
    address: 'No. 36 Mahiyawa Road, Kandy',
    phone: '+94 81 220 7755',
    hours: '9:00 AM – 6:30 PM',
    services: ['OPD', 'Laboratory', 'Eye Care', 'Pharmacy'],
    rating: 4.1,
    distance: '6.2 km',
    available: true,
    tag: 'private',
    coords: { lat: 7.2640, lng: 80.6550 },
    doctor_available: false,
  },
  {
    id: 12,
    name: 'Kandy North Polyclinic',
    type: 'Government Clinic',
    area: 'Katugastota',
    address: 'Katugastota Junction, Kandy',
    phone: '+94 81 221 9900',
    hours: '8:00 AM – 4:00 PM (Weekdays)',
    services: ['OPD', 'Vaccination', 'Dental', 'Maternal Health'],
    rating: 4.0,
    distance: '4.8 km',
    available: true,
    tag: 'govt',
    coords: { lat: 7.3100, lng: 80.6260 },
    doctor_available: true,
  },
];

// Helper to get centers with local persistence
export const getCenters = () => {
  const saved = localStorage.getItem('mc_data');
  if (saved) return JSON.parse(saved);
  return INITIAL_CENTERS;
};

// Helper to save centers
export const saveCenters = (data) => {
  localStorage.setItem('mc_data', JSON.stringify(data));
};
